version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '**/*'
    schedule:
      interval: 'weekly'
    groups:
      security-updates:
        applies-to: 'security-updates'
        patterns:
          - '*'
      version-updates:
        applies-to: 'version-updates'
        patterns:
          - '*'
